Power Query M Formulas:

To replace Null in one column with values from other. The Column to look at is ID.1, the column to take the new value is ID. Used in Warranty Recovery File.

= Table.ReplaceValue(
    #"Reordered Columns1",
    each [ID.1],  // Activa el procesamiento para TODAS las filas
    each if [ID.1] = null 
         then [ID]
         else [ID.1],  
    Replacer.ReplaceValue,   // "Usa siempre el valor calculado (new)"
    {"ID.1"}          // Aplica solo a esta columns
)

Variation with Nested If.
= Table.ReplaceValue(
    #"Reordered Columns1",
    each [CATEGORY],  // Activa el procesamiento para TODAS las filas
    each if [CATEGORY] = null and [Order Number] <> null then "NOT IN MSH020 - OLD ORDER" //First Tag Category
    else if [CATEGORY] = null and [Book of account] = "AP0" or [Book of account] = "RV0" then "FREIGHT EXPENSES" //Second Tag Category
    else if [CATEGORY] = null and [Book of account] = "AR0" or [Book of account] = "BA1" then "CREDIT CUSTOMER MANUAL" //Third Tag Category
    else if [CATEGORY] = null then "OTHERS" //Last Tag Category
    else [CATEGORY],  
    Replacer.ReplaceValue,   
    {"CATEGORY"}          // Aplica solo a esta columna
)


Variation of previous formula but with multiplication.

= Table.ReplaceValue(#"Changed Type3",
each [Amount USD],
each if [Inv Currency] <> "USD" then [Amount Local] * [FX Group] else [Amount USD],
Replacer.ReplaceValue,{"Amount USD"})

//Converted to a list to be able to call multiples steps in other queries.
https://www.youtube.com/watch?v=weafpG2yG1w&t=393s

//Make parameter for the source, and stage the path for the other queries video and min 8:38:
	https://youtu.be/D6ho5zOwZnA?si=8ENlqTJMEUe7uKVd&t=518

//Substitute Values from Other Query columns:
	https://www.thebiccountant.com/2017/07/23/transforming-a-column-with-values-from-another-column-in-powerbi-and-powerquery-in-excel/

//Create new Table base on another table Power Query:
https://community.fabric.microsoft.com/t5/Power-Query/How-to-Create-a-New-Table-from-existing-table-using-IN-POWER/td-p/1329301



